### ISSUE TITLE
Migrate to Gatsby

### ISSUE THREAD

**Issue by ziflex** [MontFerret/montferret.github.io#15]
Hugo is a nice tool but it’s pretty inconvenient to build interactive webpages.
Plus, it’s API is kinda difficult to remember if you don’t use it too often which slows down the progress.

I have worked with Gatsby little bit before and I got very good impression of the tool. And what’s more important - it’s very extensible, something that Hugo lacks.

One of the biggest reasons why I want to move to Gatsby is an interactive shell for demo queries that I want to introduce. I’m not saying it’s impossible to do with Hugo, I’m just saying it will be much easier and naturally to do in Gatsby (your webpage is a React application after all).

**Comment by ziflex** [comment]
Hey @ksdme
How will it affect the work you have already done?
I know that [there is](https://www.gatsbyjs.org/docs/adding-markdown-pages/) a plug-in for Gatsby that allows you to use plain markdown files as pages.

**Comment by ksdme** [comment]
As long as the base theme that we end up using adequately styles the page and there is a way to turn markdown into pages or generate a page itself by fixing up https://github.com/MontFerret/montferret.github.io/blob/dev/templates/docs/stdlib.template, we should be fine.

**Comment by ziflex** [comment]
Great! I’m not planning to change theme any time soon, so we are good.
