### ISSUE TITLE
RSS or do I have to write a scraper in ferret to subscribe to the blog?

### ISSUE THREAD

**Issue by brasilikum** [MontFerret/montferret.github.io#23]
I mean that's cool, but maybe you could add an rss feed, so people can subscribe.

Ferret is absolutely awesome, thanks for making it open source in any case.

**Comment by ziflex** [comment]
Hey, glad you like Ferret!

That's a great idea and we definitely need to implement it, thanks!

**Comment by ziflex** [comment]
hey, here it is.

https://www.montferret.dev/blog/index.xml

It turned out, we always had it, but didn't add the url to the web page :)

**Comment by brasilikum** [comment]
Nice! Thank you, I already subscribed
